### ISSUE TITLE
Remove support for landscape mode

### ISSUE THREAD

**Issue by Gerzer** [wtg/Shuttle-Tracker-SwiftUI-2.0#25]
The UI layout in landscape mode is currently broken. We should remove support for landscape mode until we can fix the layout issues.

**Comment by M1zz** [comment]
can you assign me?

**Comment by Gerzer** [comment]
> can you assign me?

We generally don't explicitly assign issues to people who aren't on the core team. However, you should feel free to fork the repository, to make the change, and then to submit a pull request. I look forward to your contributions!
